version: '3.8'

services:
  db:
    image: postgres:15
    container_name: homeps_db
    environment:
      POSTGRES_DB: homeps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - homeps_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeps_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/homeps
      DB_USER: postgres
      DB_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
    networks:
      - homeps_network

networks:
  homeps_network:
    driver: bridge

volumes:
  postgres_data:

